### ISSUE TITLE
Support JSONC

### ISSUE THREAD

**Issue by munierujp** [azu/rc-config-loader#11]
cf. [mocha/config.js at master · mochajs/mocha](https://github.com/mochajs/mocha/blob/master/lib/cli/config.js)

**Comment by azu** [comment]
Currently, rc-config-loader support JSON as [JSON5](https://github.com/json5/json5).
It also support comment.

Could you tell me pros and cons of JSON?

**Comment by munierujp** [comment]
> Currently, rc-config-loader support JSON as JSON5.

Oh, I didn't know that...
Now, No need to support JSONC 😄
