### ISSUE TITLE
Module not found: Can't resolve 'module'

### ISSUE THREAD

**Issue by ravecat** [azu/rc-config-loader#2]
Try to use cosmiconfig without any use

```
const rcfile = require("rc-config-loader");
```

and get error

> ./node_modules/rc-config-loader/node_modules/require-from-string/index.js
Module not found: Can't resolve 'module' in '/home/max/project/mendeleev/node_modules/rc-config-loader/node_modules/require-from-string'

```
"rc-config-loader": "^2.0.2",
node: 8.12.0
```

**Comment by azu** [comment]
Thanks for reports.

I try to reproduce it, but I can not reproduce it.

- Repo: https://github.com/azu/rc-config-loader-issue-2

```
✈ node -v
v8.12.0
~/.ghq/github.com/azu/rc-config-loader-issue-2
✈ cat example.js
const rcfile = require("rc-config-loader");
~/.ghq/github.com/azu/rc-config-loader-issue-2
✈ node example.js
```


Related:

- https://github.com/davidtheclark/cosmiconfig/issues/161

**Comment by azu** [comment]
I've seen same error(Module not found: Can't resolve 'module') on webpack.

* [Can't resolve 'module' in '...../node_modules/prettier' · Issue #4879 · prettier/prettier](https://github.com/prettier/prettier/issues/4879 "Can't resolve 'module' in '...../node_modules/prettier' · Issue #4879 · prettier/prettier")
* [Module not found: Error: Can't resolve 'module' in '...' · Issue #5423 · webpack/webpack](https://github.com/webpack/webpack/issues/5423 "Module not found: Error: Can't resolve 'module' in '...' · Issue #5423 · webpack/webpack")

Is this issue related to that?

**Comment by ravecat** [comment]
I create branch that reproduce issue

## Reproduction

1. `git clone https://github.com/ravecat/mendeleev.git --single-branch --branch rc-config-loader-issue`
2. `yarn`

I have code in `src/common/Media/responsive/index.js`

```javascript
/* eslint-disable */
import { css } from "styled-components";
const rcfile = require("rc-config-loader");

const responsive = (property, resolution) => {
  console.log(rcfile('sct'))

  return css`
    @media (max-width: ${resolution}px) {
      ${property};
    }
  `;
}

export default responsive;
```

In same folder I also exist `.sctrc` file

**Comment by ravecat** [comment]
> I've seen same error(Module not found: Can't resolve 'module') on webpack.
> 
> * [Can't resolve 'module' in '...../node_modules/prettier' · Issue #4879 · prettier/prettier](https://github.com/prettier/prettier/issues/4879)
> * [Module not found: Error: Can't resolve 'module' in '...' · Issue #5423 · webpack/webpack](https://github.com/webpack/webpack/issues/5423)
> 
> Is this issue related to that?

I need check, probably it's related

**Comment by azu** [comment]
Thanks.

<details>
<summary>I tried this repository and `yarn test` work fine in my env.</summary>
<pre>
~/.ghq/github.com/azu/testa/mendeleev
$ node -v
v8.12.0
~/.ghq/github.com/azu/testa/mendeleev 
$ yarn -v
1.9.4
$ yarn 
# install..
$ yarn test
 PASS  src/common/Media/responsive/index.test.js
  ● Console

    console.log src/common/Media/responsive/index.js:6
      { config: { responsive: [ 1023, 1600 ] },
        filePath: '/Users/azu/.ghq/github.com/azu/testa/mendeleev/.sctrc' }

 PASS  src/App.test.js
  ● Console

    console.log src/common/Media/responsive/index.js:6
      { config: { responsive: [ 1023, 1600 ] },
        filePath: '/Users/azu/.ghq/github.com/azu/testa/mendeleev/.sctrc' }
    console.log src/common/Media/responsive/index.js:6
      { config: { responsive: [ 1023, 1600 ] },
        filePath: '/Users/azu/.ghq/github.com/azu/testa/mendeleev/.sctrc' }
    console.log src/common/Media/responsive/index.js:6
      { config: { responsive: [ 1023, 1600 ] },
        filePath: '/Users/azu/.ghq/github.com/azu/testa/mendeleev/.sctrc' }
    console.log src/common/Media/responsive/index.js:6
      { config: { responsive: [ 1023, 1600 ] },
        filePath: '/Users/azu/.ghq/github.com/azu/testa/mendeleev/.sctrc' }


Test Suites: 3 passed, 3 total
Tests:       4 passed, 4 total
Snapshots:   0 total
Time:        14.001s
Ran all test suites.

Watch Usage: Press w to show more.

✨  Done in 31.79s.
</pre>
</details>

But, I've confirmed that `yarn start` is failed.

![image](https://user-images.githubusercontent.com/19714/49080243-59be8e00-f286-11e8-81d7-884395701599.png)

This error is caused by webpack.
Because, webpack can not treat `module` module.

- https://github.com/webpack/webpack/issues/5423

You can avoid this error with following patch.

```diff
diff --git a/config/webpack.config.dev.js b/config/webpack.config.dev.js
index 36d1767..6da9f84 100644
--- a/config/webpack.config.dev.js
+++ b/config/webpack.config.dev.js
@@ -118,6 +118,7 @@ module.exports = {
   node: {
     dgram: "empty",
     fs: "empty",
+    module: "empty",
     net: "empty",
     tls: "empty",
     child_process: "empty"
diff --git a/config/webpack.config.prod.js b/config/webpack.config.prod.js
index 047b7f8..5399e97 100644
--- a/config/webpack.config.prod.js
+++ b/config/webpack.config.prod.js
@@ -203,6 +203,7 @@ module.exports = {
   node: {
     dgram: "empty",
     fs: "empty",
+    module: "empty",
     net: "empty",
     tls: "empty",
     child_process: "empty"
```

I've submitted a PR to fix this issue.

- https://github.com/ravecat/mendeleev/pull/5

**Comment by ravecat** [comment]
@azu thank you very match, I will include your solution in extended functionality!

**Comment by azu** [comment]
No problem.

**Comment by ravecat** [comment]
@azu Sorry for interrupt, but I want to clarify some questions

Accorind sources, if I haven't options `rc-config-loader` use default path for search - current directory

```
const configFileName = opts.configFileName || `.${pkgName}rc`;
```

So I use loader  without options and get `undefined`. Code available like previous comment 

1. `git clone https://github.com/ravecat/mendeleev.git --single-branch --branch rc-config-loader-issue`
2. `yarn`

I have code in `src/common/Media/helpers/getConfig.js`

```javascript
const rcfile = require("rc-config-loader");

const getConfig = () => {
  console.log(rcfile("sct"));
 
  debugger
  return 
}

export default getConfig
```

and try to use in `src/common/Media/responsive/index.js`

```javascript
import { css } from "styled-components";
import getConfig from '../helpers/getConfig'

const responsive = (property, resolution) => {
  const resolutions = getConfig()

  return css`
    @media (max-width: ${resolution}px) {
      ${property};
    }
  `;
}

export default responsive;

```

Probably it's  again webpack settings relative with resolve options, but I use relative path, not absolute

**Comment by azu** [comment]
Can you create it as new issue?

**Comment by ravecat** [comment]
@azu yep, here https://github.com/azu/rc-config-loader/issues/3
