### ISSUE TITLE
How about supporting TypeScript file?

### ISSUE THREAD

**Issue by munierujp** [azu/rc-config-loader#24]
Writing configuration files in TypeScript is useful in preventing typographical and type errors.

```ts
import type {Config} from 'jest';

const config: Config = {
  verbose: true,
};

export default config;
```

https://jestjs.io/ja/docs/configuration

In [cosmiconfig](https://www.npmjs.com/package/cosmiconfig), TypeScript is supported  by the third-party [cosmiconfig-typescript-loader](https://www.npmjs.com/package/cosmiconfig-typescript-loader).
How about supporting TypeScript file?

**Comment by azu** [comment]
Related 

- #19

**Comment by azu** [comment]
I have looked at this again and many of the use cases will be the type to the whole Config like `Config`.
Therefore, we think that it would be less expensive to use TSDoc for .js.

- [Type hints on pure .js files - DEV Community](https://dev.to/manuartero/type-hints-on-pure-js-files-8ee)
- [Using Typescript without compilation - DEV Community](https://dev.to/thepassle/using-typescript-without-compilation-3ko4)

Documents and Examples are welcome!

**Comment by munierujp** [comment]
@azu I have understood the disadvantages of supporting TypeScript. Thank you!
