### ISSUE TITLE
Doesn't work well with webpack

### ISSUE THREAD

**Issue by iljapostnovs** [azu/rc-config-loader#25]
Because of dynamic require webpack can't work well with this package.
![image](https://github.com/azu/rc-config-loader/assets/31005247/7ae64037-0c6b-445b-9e41-b88d55e5a671)
![image](https://github.com/azu/rc-config-loader/assets/31005247/d73ee2e8-6ae7-4839-8a37-177e32231340)

Can it be replaced with e.g. `fs.readFile`?

**Comment by azu** [comment]
Thanks for report.

I agree it. Probably we can replace it to use fs.
https://github.com/azu/rc-config-loader/blob/1796ca800582a2710ef8c94aa0703f9f4a7b5ba7/src/rc-config-loader.ts#L145
```diff
- const pkgJSON = require(pkgJSONLoc);
+ const pkgJSON = JSON.parse(fs.readFileSync(pkgJSONLoc, "utf-8"));
```

However, I don't think webpack can bundle files that are loaded dynamically, even if you use fs.

**Comment by iljapostnovs** [comment]
> 



> Thanks for report.
> 
> I agree it. Probably we can replace it to use fs.
> 
> https://github.com/azu/rc-config-loader/blob/1796ca800582a2710ef8c94aa0703f9f4a7b5ba7/src/rc-config-loader.ts#L145
> 
> ```diff
> - const pkgJSON = require(pkgJSONLoc);
> + const pkgJSON = JSON.parse(fs.readFileSync(pkgJSONLoc, "utf-8"));
> ```
> 
> However, I don't think webpack can bundle files that are loaded dynamically, even if you use fs.

It can't, that's true, but we don't need it.
However, webpack will not cause any warnings and everything will work as expected.

I was using this package for reading config files in my own project, and it was working fine by itself, but when it's bundled by webpack, this package was not working as expected anymore for god knows which reasons.
I tested it with `readFile` instead and everything works as expected with that.

Thank you a lot for your package!
If we can get it working with webpack, it would be fantastic :)
